---
name: practical-07
break: true
indent: 4
---
src/main:
    java:
        centile/DisplayCentile.java:
            ConfirmFileExists
            MatchFileRegex --regex "Fraction\s[A-Za-z0-9]+ = new" --count 1 --exact
            MatchFileFragment --fragment ".centile()" --count 1 --exact
            MatchFileFragment --fragment ".fmtPercent()" --count 1 --exact
            MatchFileFragment --fragment ".toString()" --count 2 --exact

src/main:
    java:
        centile/Fraction.java:
            ConfirmFileExists
            MatchFileFragment --fragment "= NumberFormat.getCurrencyInstance();" --count 1 --exact
            MatchFileRegex --regex "return\s[a-zA-Z0-9]+\.format\(amount\);" --count 1 --exact


ExecuteCommand --command "gradle build"
MatchCommandRegex --command "gradle run --args='184.80'" --regex "(-)?(\()?\$[0-9]+\.[0-9]{2}(\))?" --count 2 --exact
MatchCommandRegex --command "gradle run --args='184.80'" --regex "Wiz\sHats\sUnlimited" --count 1 --exact  
